/**
 * Narasi.js - Narrative Text Component
 * Rich text narrative component for NexaReactive
 */

import { initData } from "./Percent/index.js";

class Narasi {
  constructor(interactions) {
    this.interactions = interactions;
    this.config = interactions.config;
    this.nexaUI = interactions.nexaUI;
  }

  /**
   * Create a narrative text element
   */
  createNarasi(
    title = "Narasi",
    content = "This is a sample narasi content..."
  ) {
    const narasiId = `narasi-${Date.now()}`;

    const narasiHTML = `
      <div class="nexa-narasi-container" id="${narasiId}" style="
        width: 100%;
        margin: 10px 0;
        padding: 0;
        border: 1px solid #ddd;
        border-radius: 8px;
        background: #ffffff;
        box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        font-family: 'Calibri', 'Arial', sans-serif;
        line-height: 1.5;
      ">
        <!-- Document Header -->
        <div class="nexa-narasi-header" style="
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          padding: 25px 30px;
          border-radius: 8px 8px 0 0;
          position: relative;
        ">
          <div class="nexa-narasi-title" style="
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 8px;
            text-shadow: 0 1px 2px rgba(0,0,0,0.3);
          ">${title}</div>
          <div class="nexa-narasi-meta" style="
            font-size: 13px;
            opacity: 0.9;
            display: flex;
            align-items: center;
            gap: 20px;
          ">
            <span>📝 Laporan Dokumen</span>
            <span>•</span>
            <span>${new Date().toLocaleDateString("id-ID", {
              year: "numeric",
              month: "long",
              day: "numeric",
            })}</span>
            <span>•</span>
            <span>Generated by NexaReactive</span>
          </div>
        </div>
        
        <!-- Document Content -->
        <div class="nexa-narasi-content" style="
          padding: 30px;
          color: #333;
          font-size: 14px;
          line-height: 1.8;
        ">
          <div style="
            background: #f8f9fa;
            padding: 20px;
            border-left: 4px solid #007bff;
            border-radius: 4px;
            margin-bottom: 20px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
          ">
            ${content}
          </div>
          
          <!-- Document Footer -->
          <div class="nexa-narasi-footer" style="
            margin-top: 30px;
            padding-top: 20px;
            border-top: 2px solid #e9ecef;
            display: flex;
            justify-content: space-between;
            align-items: center;
            flex-wrap: wrap;
            gap: 15px;
          ">
            <div style="
              font-size: 12px;
              color: #6c757d;
              display: flex;
              align-items: center;
              gap: 10px;
            ">
              <span>📄 Halaman 1 dari 1</span>
              <span>•</span>
              <span>Dokumen ini dibuat secara otomatis</span>
            </div>
            
            <div class="nexa-narasi-actions" style="
              display: flex;
              gap: 8px;
              flex-wrap: wrap;
            ">
              <button class="nexa-narasi-btn edit" style="
                background: #007bff;
                color: white;
                border: none;
                padding: 8px 16px;
                border-radius: 4px;
                cursor: pointer;
                font-size: 12px;
                transition: all 0.2s;
                box-shadow: 0 1px 3px rgba(0,0,0,0.2);
              " onmouseover="this.style.background='#0056b3'; this.style.transform='translateY(-1px)'" onmouseout="this.style.background='#007bff'; this.style.transform='translateY(0)'">
                ✏️ Edit
              </button>
              <button class="nexa-narasi-btn copy" style="
                background: #28a745;
                color: white;
                border: none;
                padding: 8px 16px;
                border-radius: 4px;
                cursor: pointer;
                font-size: 12px;
                transition: all 0.2s;
                box-shadow: 0 1px 3px rgba(0,0,0,0.2);
              " onmouseover="this.style.background='#1e7e34'; this.style.transform='translateY(-1px)'" onmouseout="this.style.background='#28a745'; this.style.transform='translateY(0)'">
                📋 Copy
              </button>
              <button class="nexa-narasi-btn delete" style="
                background: #dc3545;
                color: white;
                border: none;
                padding: 8px 16px;
                border-radius: 4px;
                cursor: pointer;
                font-size: 12px;
                transition: all 0.2s;
                box-shadow: 0 1px 3px rgba(0,0,0,0.2);
              " onmouseover="this.style.background='#c82333'; this.style.transform='translateY(-1px)'" onmouseout="this.style.background='#dc3545'; this.style.transform='translateY(0)'">
                🗑️ Delete
              </button>
            </div>
          </div>
        </div>
      </div>
    `;

    return narasiHTML;
  }

  


